server:
  port: 7001

# Eureka配置
eureka:
  instance:
    hostname: localhost #服务端，这里写咱们本机地址就ok
  client:
    register-with-eureka: false #是否向注册中心注册自己
    fetch-registry: false #如果为false即表示自己为注册中心
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
