spring:
  profiles:
    #激活配置文件
    active: prod
  #配置静态资源路径
  resources:
    static-locations: classpath:/static/

#日志相关
logging:
  #配置文件日志路径
  config: classpath:logback-spring.xml

#微信相关配置
wx:
  #appId （到时候换成自己公众号的）
  appId: wx326eef0f53c7d587
  #appSecret（到时候换成自己公众号的）
  appSecret: 850958ff77d51eb03b7d5c142628878b
  #参考以下文档获取access_token（有效期7200秒，开发者必须在自己的服务全局缓存access_token）
  jssdk_accesstoken_url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
  #用第一步拿到的access_token 采用http GET方式请求获得jsapi_ticket（有效期7200秒，开发者必须在自己的服务全局缓存jsapi_ticket）
  jssdk_getticket_url: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=ACCESS_TOKEN&type=jsapi