server:
  port: 8002
#  config-location: classpath:mybatis/mybatis-config.xml
#  mybatis
mybatis:
  type-aliases-package: com.xiaozhoubg.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

#spring
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka,http://eureka7001.com:7001/eureka
  instance:
    instance-id: springcloud-dept-8002

info:
  app.name: 模块名称
  company.name: 公司名称
  xiaozhoubg: xiaozhoubg
